# API Configuration
api_key: ""
api_secret: ""
discord_webhook_url: ""

# Core Strategy Settings
leverage: 15                # Trading leverage
min_notional: 15            # Minimum trade size in USDT

# Auto-compounding settings
compounding:
  enable_compounding: true
  base_min_notional: 15.0         # Always use at least $15
  compounding_percentage: 1       # Use percentage of balance as notional

# Pair age filtering
pair_age:
  min_age_days: 3               # Minimum age in days before trading a pair
  enable_age_filter: true       # Enable/disable the age filter
  cache_duration_hours: 24      # How long to cache age data
  api_timeout_seconds: 10       # Timeout for API requests

# Pair Filter
pair_filter:
  enable_whitelist: false           # Set to true to only trade whitelisted pairs
  enable_blacklist: true            # Set to true to avoid blacklisted pairs
  whitelist_file: "whitelist.txt"   # File containing allowed pairs
  blacklist_file: "blacklist.txt"   # File containing blocked pairs
  auto_reload: true                 # Auto-reload filter files
  reload_interval_minutes: 5        # How often to reload (minutes)

# RapidAPI Configuration
rapidapi:
  api_key: ""
  base_url: "https://liquidation-report.p.rapidapi.com"
  endpoint: "/lickhunterpro"
  update_interval_minutes: 5          # Fetch fresh data every 5 minutes
  timeout_seconds: 30                 # API request timeout
  retry_attempts: 3                   # Number of retry attempts
  retry_delay: 5.0                    # Delay between retries (seconds)
  enable_caching: true                # Cache data locally
  cache_file: "price_zones_cache.json"

# VWAP Configuration
vwap:
  period: 200                # VWAP calculation period
  long_offset_pct: 0.8       # Default long offset percentage
  short_offset_pct: 0.8      # Default short offset percentage
  use_rapidapi_zones: true   # Use RapidAPI zones as primary signal
  vwap_enhancement: true     # Enhance with real-time VWAP

# DCA System
dca:
  enable: true
  max_levels: 5   # Maximum DCA levels (user configurable)

  # DCA trigger percentages (adverse move %)
  trigger_pcts:
    - 0.04
    - 0.07
    - 0.10
    - 0.13
    - 0.16

  # DCA size multipliers
  size_multipliers:
    - 1.5
    - 2.0
    - 2.5
    - 3.0
    - 3.5

# Profit Protection System
profit_protection:
  initial_tp_pct: 0.005       # Fixed TP
  enable_stop_loss: false     # Enable SL
  stop_loss_pct: 0.015         # Fixed SL

# Market Regime Detection
market_regime:
  adx_period: 21
  atr_period: 21
  trend_threshold: 25.0      # ADX above = trending market
  range_threshold: 18.0      # ADX below = ranging market
  volatility_multiplier: 2.0 # ATR spike detection multiplier
  regime_filter: true        # Filter trades based on market regime

# Momentum Detection
momentum:
  enable_momentum_filter: true

  # Daily thresholds
  daily_pump_threshold: 20.0    # Avoid if pumped in 24h
  daily_dump_threshold: -15.0   # Avoid if dumped in 24h

  # Hourly thresholds  
  hourly_pump_threshold: 10.0    # Avoid if pumped in 1h
  hourly_dump_threshold: -8.0   # Avoid if dumped in 1h

  # Volatility limits
  min_daily_volatility: 2.0     # Avoid if daily range
  max_daily_volatility: 60.0    # Avoid if daily range

# Risk Management
risk:
  isolation_pct: 0.50
  max_positions: 2
  min_24h_volume: 15000000   # Minimum daily volume

# System Settings
enable_discord: true
log_file: "0xliqd.log"
pairs_file: "trading_pairs_auto.json"

# Debug Settings
debug:
  enable_trade_debug: true        # Logs detailed trade info
  enable_filter_debug: true       # Logs detailed filter info
  enable_data_debug: true         # Logs detailed data info
  log_all_liquidations: true      # Log all liquidation events
  stats_interval_minutes: 15      # Stats logging interval