# API Configuration
api_key: ""
api_secret: ""
discord_webhook_url: ""

# Core Strategy Settings
leverage: 10                # Trading leverage
min_notional: 11            # Minimum trade size in USDT

# RapidAPI Configuration
rapidapi:
  api_key: ""
  base_url: "https://liquidation-report.p.rapidapi.com"
  endpoint: "/lickhunterpro"
  update_interval_minutes: 5          # Fetch fresh data every 5 minutes
  timeout_seconds: 30                 # API request timeout
  retry_attempts: 3                   # Number of retry attempts
  retry_delay: 5.0                    # Delay between retries (seconds)
  enable_caching: true                # Cache data locally
  cache_file: "price_zones_cache.json"

# VWAP Configuration
vwap:
  period: 200                # VWAP calculation period
  long_offset_pct: 0.8       # Default long offset percentage
  short_offset_pct: 0.8      # Default short offset percentage
  use_rapidapi_zones: true   # Use RapidAPI zones as primary signal
  vwap_enhancement: true     # Enhance with real-time VWAP

# Smart DCA System
dca:
  enable: true
  max_levels: 7              # Maximum DCA levels (user configurable)
  
  # DCA trigger percentages (adverse move %)
  trigger_pcts:
    - 0.05  # DCA level 1
    - 0.07  # DCA level 2
    - 0.09  # DCA level 3
    - 0.11  # DCA level 4
    - 0.13  # DCA level 5
    - 0.15  # DCA level 6
    - 0.17  # DCA level 7
  
  # DCA size multipliers
  size_multipliers:
    - 2.0    # Level 1
    - 3.0    # Level 2
    - 4.0    # Level 3
    - 5.0    # Level 4
    - 6.0    # Level 5
    - 7.0    # Level 6
    - 8.0    # Level 7

# Profit Protection System
profit_protection:
  initial_tp_pct: 0.00484    # Fixed TP
  enable_stop_loss: false    # Enable SL
  stop_loss_pct: 0.02        # Fixed SL

# Market Regime Detection
market_regime:
  adx_period: 14
  atr_period: 14
  trend_threshold: 25.0      # ADX above = trending market
  range_threshold: 20.0      # ADX below = ranging market
  volatility_multiplier: 2.0 # ATR spike detection multiplier
  regime_filter: true        # Filter trades based on market regime

# Momentum Detection
momentum:
  enable_momentum_filter: true
  
  # Daily thresholds
  daily_pump_threshold: 12.0    # Avoid if pumped in 24h
  daily_dump_threshold: -12.0   # Avoid if dumped in 24h
  
  # Hourly thresholds  
  hourly_pump_threshold: 5.0    # Avoid if pumped in 1h
  hourly_dump_threshold: -5.0   # Avoid if dumped in 1h
  
  # Volatility limits
  min_daily_volatility: 3.0     # Avoid if daily range
  max_daily_volatility: 30.0    # Avoid if daily range
  
  # Strategy mode
  momentum_mode: "AVOID_EXTREMES"  # AVOID_EXTREMES, TARGET_MOMENTUM, ENHANCE_SIGNALS

# Risk Management
risk:
  isolation_pct: 1.0
  max_positions: 2
  min_24h_volume: 10000000   # Minimum $10M daily volume

# System Settings
enable_discord: true
log_file: "0xliqd.log"
pairs_file: "trading_pairs_auto.json"

# Debug Settings
debug:
  enable_trade_debug: true    # Logs detailed trade info
  enable_filter_debug: true   # Logs detailed filter info
  enable_data_debug: true     # Logs detailed data info
  log_all_liquidations: true  # Log all liquidation events
  stats_interval_minutes: 60  # Stats logging interval
